### RNN Embedding workout

In [41]:
from tensorflow.keras.preprocessing.text import one_hot

In [42]:
sent =[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'not understand the meaning of words',
    'the glass is half empty',
    'the glass is half full'
    ]

In [43]:
voc_size=10000

In [44]:
one_hot_rep =  [one_hot(words,voc_size) for words in sent]


In [45]:
one_hot_rep

[[8867, 1235, 1900, 9826],
 [8867, 1235, 1900, 9311],
 [8867, 8611, 1900, 8320],
 [2757, 2089, 5063, 8958, 9421],
 [2757, 2089, 5063, 8958, 6083],
 [8822, 8867, 8405, 1900, 7823],
 [7475, 8822, 8867, 8405, 1900, 7823],
 [8867, 1235, 5834, 9270, 1619],
 [8867, 1235, 5834, 9270, 7755]]

In [46]:
## word embedding Representation 

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [47]:
sent_length=8
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8867 1235 1900 9826]
 [   0    0    0    0 8867 1235 1900 9311]
 [   0    0    0    0 8867 8611 1900 8320]
 [   0    0    0 2757 2089 5063 8958 9421]
 [   0    0    0 2757 2089 5063 8958 6083]
 [   0    0    0 8822 8867 8405 1900 7823]
 [   0    0 7475 8822 8867 8405 1900 7823]
 [   0    0    0 8867 1235 5834 9270 1619]
 [   0    0    0 8867 1235 5834 9270 7755]]


In [48]:
# Feature Representation 

dim = 10

model = Sequential([
    Embedding(
        input_dim=voc_size,
        output_dim=dim,
        input_shape=(sent_length,)
    )
])

model.compile(optimizer='adam', loss='mse')

model.summary()


Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [49]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step


array([[[ 0.00064716, -0.02656808,  0.01879739,  0.04396709,
          0.02476198, -0.03284894, -0.00354484,  0.00399679,
         -0.021345  ,  0.04339469],
        [ 0.00064716, -0.02656808,  0.01879739,  0.04396709,
          0.02476198, -0.03284894, -0.00354484,  0.00399679,
         -0.021345  ,  0.04339469],
        [ 0.00064716, -0.02656808,  0.01879739,  0.04396709,
          0.02476198, -0.03284894, -0.00354484,  0.00399679,
         -0.021345  ,  0.04339469],
        [ 0.00064716, -0.02656808,  0.01879739,  0.04396709,
          0.02476198, -0.03284894, -0.00354484,  0.00399679,
         -0.021345  ,  0.04339469],
        [ 0.04904303, -0.01228118,  0.01151743, -0.00210524,
          0.01731858,  0.03616327, -0.00096786,  0.0262879 ,
         -0.0289868 ,  0.04759203],
        [-0.0454471 , -0.02709402,  0.00753976,  0.03555918,
         -0.02092711, -0.01231371,  0.04650483,  0.00546543,
          0.04941324,  0.04738518],
        [-0.01637508,  0.01635709,  0.03630867,  0.0

In [50]:
embedded_docs[0]

array([   0,    0,    0,    0, 8867, 1235, 1900, 9826], dtype=int32)

In [52]:
model.predict(embedded_docs)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step


array([[ 0.00064716, -0.02656808,  0.01879739,  0.04396709,  0.02476198,
        -0.03284894, -0.00354484,  0.00399679, -0.021345  ,  0.04339469],
       [ 0.00064716, -0.02656808,  0.01879739,  0.04396709,  0.02476198,
        -0.03284894, -0.00354484,  0.00399679, -0.021345  ,  0.04339469],
       [ 0.00064716, -0.02656808,  0.01879739,  0.04396709,  0.02476198,
        -0.03284894, -0.00354484,  0.00399679, -0.021345  ,  0.04339469],
       [ 0.00064716, -0.02656808,  0.01879739,  0.04396709,  0.02476198,
        -0.03284894, -0.00354484,  0.00399679, -0.021345  ,  0.04339469],
       [ 0.04904303, -0.01228118,  0.01151743, -0.00210524,  0.01731858,
         0.03616327, -0.00096786,  0.0262879 , -0.0289868 ,  0.04759203],
       [-0.0454471 , -0.02709402,  0.00753976,  0.03555918, -0.02092711,
        -0.01231371,  0.04650483,  0.00546543,  0.04941324,  0.04738518],
       [-0.01637508,  0.01635709,  0.03630867,  0.00099572, -0.01760073,
         0.00127836,  0.03344711, -0.02515464